apiVersion: v1 
kind: PersistentVolume 
metadata:
  name : logstash-pv 
spec: 
  capacity:
    storage: 3Gi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path : /home/nik/Desktop/ECK/logstash/logstashVolume
